### ISSUE TITLE
Build issues on Ubuntu 12.04

### ISSUE THREAD

**Issue by reedlaw** [gameoverhack/ofxOpenNI#29]
I get these:

```
obj/x86_64Release/addons/ofxOpenNI/src/ofxOpenNITypes.o: In function `ofxOpenNIROI::set(ofVec3f, ofVec3f)':
ofxOpenNITypes.cpp:(.text._ZN12ofxOpenNIROI3setE7ofVec3fS0_[ofxOpenNIROI::set(ofVec3f, ofVec3f)]+0x1e5): undefined reference to `ofRectangle::set(ofVec3f const&, float, float)'
ofxOpenNITypes.cpp:(.text._ZN12ofxOpenNIROI3setE7ofVec3fS0_[ofxOpenNIROI::set(ofVec3f, ofVec3f)]+0x269): undefined reference to `ofRectangle::set(ofVec3f const&, float, float)'
obj/x86_64Release/addons/ofxOpenNI/src/ofxOpenNI.o: In function `ofxOpenNI::stop()':
ofxOpenNI.cpp:(.text+0x93ee): undefined reference to `ofThread::stopThread()'
collect2: ld returned 1 exit status
make: *** [bin/3DJ_Test] Error 1
```

I am using OF 0073 and OpenNI 2.0.0.29 Beta (Linux64).

**Comment by reedlaw** [comment]
I fixed it, so I'll leave a note here for anyone else who might have the same issue.

After upgrading from OF 0071 to 0073 I had to recompile OF using the scripts/linux/compileOF.sh script.
